### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by udoprog** [reproto/reproto#12]
@coder543 is currently testing out the build on Windows. Moving this as a tracking issue here instead.

So far:
 - [x] https://github.com/udoprog/genco/issues/1 - `con` is a reserved filename which caused genco to not compile.
 - [x] Issues with compiling `onig-sys`, @coder543 could you elaborate? "[..] just dealing with trying to get the onig-sys library to compile... I wish syntect just used some native-Rust regex library, [but it doesn't](https://github.com/trishume/syntect/issues/12)."
 - [ ] Bad path in [themes generator](/reproto/reproto/blob/master/lib/backend-doc/build.rs#L133)
 - [ ] Text Coloring Broken Issue #14

Linked issue:
* https://github.com/trishume/syntect/issues/12

**Comment by coder543** [comment]
The main sequence was as follows:

- update Visual Studio
- figure out that not all VS tools were being exposed through a normal PowerShell prompt's PATH (such as `nmake`)
- switch to the "x64 Native Tools Command Prompt for VS 2017"
- try again

Now, I get a long sequence of these errors:

```
error: unknown character escape: U
 --> C:\Users\coder\workspace\reproto\target\debug\build\reproto-backend-doc-db163209fb11f57d\out/themes.rs:1:48
  |
1 | const DOC_CSS_DARK: &[u8] = include_bytes!("C:\Users\coder\workspace\reproto\target\debug\build\reproto-backend-doc-db163209fb11f57d\out/doc.dark.css");
  |                                                ^
```

**Comment by coder543** [comment]
I believe the problem is here: https://github.com/reproto/reproto/blob/master/lib/backend-doc/build.rs#L133

The `.display()` function _displays_ it correctly, but the backslashes are not escaped properly. Also, rather than just joining `out_path.display()` with `name` using `{}/{}`, it should really be a [path::join](https://doc.rust-lang.org/std/path/struct.Path.html#method.join), I think.

**Comment by coder543** [comment]
Once the path is joined and you call `display()` on it, I think replacing individual backslashes with double-backslashes would suffice. I looked for what kind of methods Rust offers to escape strings, and most of them seem limited to ASCII, which is not a good thing to be tied down to. [Here is an example.](https://doc.rust-lang.org/std/primitive.char.html#method.escape_default) Based on the list of replaced characters, I think the backslash is the most relevant character.

On Linux, it's certainly possible to have a file name with a newline in it and other exciting things, but I don't think it's worth worrying about.

**Comment by udoprog** [comment]
@coder543 Could you try having it emit code with the following style into themes.rs?:

```rust
/* ... */
const DOC_CSS_DARK: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/doc.dark.css"));
```

**Comment by coder543** [comment]
Changing the code to use

        writeln!(
            themes,
            "const DOC_CSS_{}: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{}\"));",
            key_upper,
            name
        )?;

worked just fine.

**Comment by udoprog** [comment]
@coder543 do you want to setup a PR?

**Comment by coder543** [comment]
I can, if you want, but this fix was mostly your idea, and it's tiny. Especially if or when stuff starts happening around issue #2, I may start really diving into the code and setting up PRs.

**Comment by udoprog** [comment]
The benefit is that you can do it in an environment where you can check it works. I'm just guessing here :). But sure. I'll do it.

What were the issues with `onig-sys`?

**Comment by coder543** [comment]
Ok, I opened a PR.

The issues with building it were related to not having the `nmake` tool from VS2017 in my environment's PATH, which was fixed by using the "x64 Native Tools Command Prompt for VS 2017" instead of PowerShell. Once the dependencies were built, I was able to switch back to the more comfortable PowerShell environment.

**Comment by udoprog** [comment]
This seems to have been fixed already.
